### ISSUE TITLE
Error loading .so library

### ISSUE THREAD

**Issue by josesj** [ryanpepper/tcl_kernel#11]
When I try to load a .so library (libfitstcl.so) in a notebook, kernel responds with message: couldn't load file "libfitstcl.so": /usr/local/lib/libfitstcl.so: undefined symbol: Tcl_GetCharLength

The library load correctly from a tclsh.

**Comment by rpep** [comment]
Hi there,

This appears to be a bug in the building of Python; we just make use of Tkinter which is built into the Python language.

See issue here for details; you can maybe try installing Python from elsewhere (such as Anaconda Python) to work around this issue.

Cheers,
Ryan

**Comment by rpep** [comment]
https://bugs.python.org/issue31817

Sorry, forgot to post the link!
