### ISSUE TITLE
Kernelspec doesn't follow Python version in use

### ISSUE THREAD

**Issue by takluyver** [ryanpepper/tcl_kernel#7]
I installed `tcl_kernel` under Python 3, which is called `python3` on Debian systems. But the kernelspec is hardcoded to run `python`.

Have a look at what we do to install the kernelspec in bash_kernel:
https://github.com/takluyver/bash_kernel/blob/master/bash_kernel/install.py

We write kernel.json with `sys.executable`, which is the path of the Python executable that's running that code.

This also provides a neat way to install the kernelspec - run `python -m bash_kernel.install`.

**Comment by rpep** [comment]
Fixed by c13ff8ee21d1
